# Generated by Django 4.0.4 on 2022-05-30 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('link_slug', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link Slug')),
                ('abs_link', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link')),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('link_slug', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link Slug')),
                ('abs_link', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link')),
                ('num_scrap', models.IntegerField(blank=True, null=True, verbose_name='Qty Scrapped')),
                ('work_no', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Work No')),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
                ('job_name', models.CharField(max_length=50, verbose_name='Job Name')),
                ('quantity', models.IntegerField(verbose_name='Qty.')),
                ('object_id', models.CharField(editable=False, max_length=30, null=True, verbose_name='Operation ID')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Complete', 'Complete'), (None, None)], default='Pending', editable=False, max_length=10, null=True, verbose_name='Job Status')),
                ('content_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('link_slug', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link Slug')),
                ('abs_link', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link')),
                ('loc_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('many_jobs', models.BooleanField(default=False, verbose_name='Many Jobs')),
                ('help_req', models.BooleanField(default=False, verbose_name='Help Needed')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapCode',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='SC-ID')),
                ('name', models.CharField(max_length=100, verbose_name='SC-ID')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='Name')),
                ('link_slug', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link Slug')),
                ('abs_link', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('op_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Operation ID')),
                ('link_slug', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link Slug')),
                ('abs_link', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link')),
                ('active', models.BooleanField(default=False, editable=False, verbose_name='Active')),
                ('display', models.BooleanField(default=True, editable=False, verbose_name='Display')),
                ('actual_set', models.FloatField(blank=True, null=True, verbose_name='Actual Set')),
                ('actual_run', models.FloatField(blank=True, null=True, verbose_name='Actual Run')),
                ('actual_insp', models.FloatField(blank=True, null=True, verbose_name='Actual Inspection')),
                ('actual_oneoff', models.FloatField(blank=True, null=True, verbose_name='Actual One-Off')),
                ('actual_fullbatch', models.FloatField(blank=True, null=True, verbose_name='Actual Full Batch')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual Start')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual End')),
                ('last_action_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last Change')),
                ('num_scrap', models.IntegerField(blank=True, null=True, verbose_name='Qty Scrapped')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Complete', 'Complete'), (None, None)], default='Pending', editable=False, max_length=10, null=True, verbose_name='Op Status')),
                ('phase', models.CharField(blank=True, choices=[(None, None), ('Pending', 'Pending'), ('Setup', 'Setup'), ('One-Off', 'One-Off'), ('Interim Inspection', 'Interim Inspection'), ('Full Batch', 'Full Batch'), ('Complete', 'Complete')], default=None, max_length=20, null=True, verbose_name='Phase')),
                ('issue_no', models.CharField(blank=True, max_length=1, null=True, verbose_name='Issue No.')),
                ('op_no', models.IntegerField(verbose_name='Op No.')),
                ('part_no', models.IntegerField(blank=True, null=True, verbose_name='Part No.')),
                ('upload_id', models.IntegerField(blank=True, null=True, verbose_name='Upload ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Op Name')),
                ('drg_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Drg No.')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Planned Finish')),
                ('planned_set', models.FloatField(blank=True, null=True, verbose_name='Planned Set Mins')),
                ('planned_run', models.FloatField(blank=True, null=True, verbose_name='Planned Run Mins')),
                ('insp_bool', models.BooleanField(default=False, verbose_name='Inspection T/F')),
                ('op_note', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note')),
                ('is_interim', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job', verbose_name='Job')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location', verbose_name='Location')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worker', verbose_name='Worker')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worker', verbose_name='Worker'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location', verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worker', verbose_name='Current Worker'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(verbose_name='Time')),
                ('undone', models.BooleanField(default=False, verbose_name='Undone')),
                ('message', models.CharField(max_length=200, verbose_name='Message')),
                ('data', models.JSONField(blank=True, default=None, null=True, verbose_name='Data')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worker')),
            ],
        ),
    ]
