# Generated by Django 4.0.4 on 2022-05-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('link_slug', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link Slug')),
                ('abs_link', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link')),
                ('work_no', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Work No')),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
                ('job_name', models.CharField(max_length=50, verbose_name='Job Name')),
                ('quantity', models.IntegerField(verbose_name='Qty.')),
                ('job_log', models.JSONField(blank=True, null=True, verbose_name='Job Log')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('link_slug', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link Slug')),
                ('abs_link', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link')),
                ('loc_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('machine', models.BooleanField(default=True, verbose_name='Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='Name')),
                ('link_slug', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link Slug')),
                ('abs_link', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('op_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Operation ID')),
                ('link_slug', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link Slug')),
                ('abs_link', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link')),
                ('issue_no', models.CharField(max_length=1, verbose_name='Issue No.')),
                ('op_no', models.IntegerField(verbose_name='Op No.')),
                ('part_no', models.IntegerField(verbose_name='Part No.')),
                ('upload_id', models.IntegerField(verbose_name='Upload ID')),
                ('op_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Op Name')),
                ('drg_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Drg No.')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Planned Finish')),
                ('planned_set', models.FloatField(blank=True, null=True, verbose_name='Planned Set Mins')),
                ('planned_run', models.FloatField(blank=True, null=True, verbose_name='Planned Run Mins')),
                ('insp_bool', models.BooleanField(default=False, verbose_name='Inspection T/F')),
                ('op_note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.job', verbose_name='Job')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location', verbose_name='Location')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operator', verbose_name='Operator')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operator', verbose_name='Operator'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operator', verbose_name='Operator'),
        ),
    ]
