# Generated by Django 4.0.4 on 2022-05-23 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('link_slug', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link Slug')),
                ('abs_link', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link')),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('link_slug', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link Slug')),
                ('abs_link', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link')),
                ('work_no', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Work No')),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
                ('job_name', models.CharField(max_length=50, verbose_name='Job Name')),
                ('quantity', models.IntegerField(verbose_name='Qty.')),
                ('job_log', models.JSONField(blank=True, null=True, verbose_name='Job Log')),
                ('object_id', models.CharField(editable=False, max_length=30, null=True, verbose_name='Operation ID')),
                ('content_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('link_slug', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link Slug')),
                ('abs_link', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link')),
                ('loc_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('many_jobs', models.BooleanField(default=False, verbose_name='Many Jobs')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapCode',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='SC-ID')),
                ('name', models.CharField(max_length=100, verbose_name='SC-ID')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='Name')),
                ('link_slug', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link Slug')),
                ('abs_link', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('op_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Operation ID')),
                ('link_slug', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link Slug')),
                ('abs_link', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Link')),
                ('active', models.BooleanField(default=False, editable=False, verbose_name='Active')),
                ('display', models.BooleanField(default=True, editable=False, verbose_name='Display')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Complete', 'Complete')], default='Pending', editable=False, max_length=10, verbose_name='Op Status')),
                ('interim_status', models.CharField(choices=[('Setup', 'Setup'), ('OneOff', 'One-off'), ('Interim', 'Interim Inspection'), ('FullBatch', 'Full Batch'), ('Pending', 'Pending'), ('Complete', 'Complete')], default='Pending', editable=False, max_length=20, verbose_name='Interim Status')),
                ('issue_no', models.CharField(max_length=1, verbose_name='Issue No.')),
                ('op_no', models.IntegerField(verbose_name='Op No.')),
                ('part_no', models.IntegerField(blank=True, null=True, verbose_name='Part No.')),
                ('upload_id', models.IntegerField(blank=True, null=True, verbose_name='Upload ID')),
                ('op_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Op Name')),
                ('drg_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Drg No.')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Planned Finish')),
                ('planned_set', models.FloatField(blank=True, null=True, verbose_name='Planned Set Mins')),
                ('planned_run', models.FloatField(blank=True, null=True, verbose_name='Planned Run Mins')),
                ('insp_bool', models.BooleanField(default=False, verbose_name='Inspection T/F')),
                ('op_note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job', verbose_name='Job')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location', verbose_name='Location')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worker', verbose_name='Worker')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worker', verbose_name='Worker'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location', verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worker', verbose_name='Current Worker'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(verbose_name='Time')),
                ('undone', models.BooleanField(default=False, verbose_name='Undone')),
                ('message', models.CharField(max_length=200, verbose_name='Message')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operation')),
                ('scrapCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.scrapcode')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worker')),
            ],
        ),
    ]
