# Generated by Django 4.0.4 on 2022-05-24 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_op_name_operation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
    ]
