# Generated by Django 4.0.4 on 2022-05-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entry_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='scrapCode',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_log',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='interim_status',
        ),
        migrations.AddField(
            model_name='entry',
            name='data',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='operation',
            name='insp_status',
            field=models.CharField(choices=[(None, 'None'), ('Pending', 'Pending'), ('Setup', 'Setup'), ('OneOff', 'One-off'), ('Interim', 'Interim Inspection'), ('FullBatch', 'Full Batch'), ('Complete', 'Complete')], default=None, editable=False, max_length=20, null=True, verbose_name='Interim Status'),
        ),
    ]
