# Generated by Django 4.0.4 on 2022-05-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_entry_scrapcode_remove_job_job_log_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='insp_status',
            new_name='phase',
        ),
    ]
