# Generated by Django 4.0.4 on 2022-05-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_insp_status_operation_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_interim',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operation',
            name='phase',
            field=models.CharField(choices=[(None, None), ('Pending', 'Pending'), ('Setup', 'Setup'), ('One-Off', 'One-Off'), ('Interim Inspection', 'Interim Inspection'), ('Full Batch', 'Full Batch'), ('Complete', 'Complete')], default=None, max_length=20, null=True, verbose_name='Phase'),
        ),
    ]
