# Generated by Django 4.0.4 on 2022-05-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_operation_issue_no_alter_operation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual End'),
        ),
        migrations.AddField(
            model_name='operation',
            name='actual_run',
            field=models.FloatField(blank=True, null=True, verbose_name='Actual Run'),
        ),
        migrations.AddField(
            model_name='operation',
            name='actual_set',
            field=models.FloatField(blank=True, null=True, verbose_name='Actual Set'),
        ),
        migrations.AddField(
            model_name='operation',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Start'),
        ),
    ]
