# Generated by Django 4.0.4 on 2022-05-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_operation_actual_end_operation_actual_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='last_change',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last Change'),
        ),
    ]
