# Generated by Django 4.0.4 on 2022-05-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_operation_last_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='actual_end',
            new_name='actual_end_time',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='actual_start',
            new_name='actual_start_time',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='last_change',
            new_name='last_change_time',
        ),
        migrations.AddField(
            model_name='operation',
            name='actual_fullbatch',
            field=models.FloatField(blank=True, null=True, verbose_name='Actual Run'),
        ),
        migrations.AddField(
            model_name='operation',
            name='actual_insp',
            field=models.FloatField(blank=True, null=True, verbose_name='Actual Run'),
        ),
        migrations.AddField(
            model_name='operation',
            name='actual_oneoff',
            field=models.FloatField(blank=True, null=True, verbose_name='Actual Run'),
        ),
    ]
