# Generated by Django 4.0.4 on 2022-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_actual_end_operation_actual_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='phase',
            field=models.CharField(blank=True, choices=[(None, None), ('Pending', 'Pending'), ('Setup', 'Setup'), ('One-Off', 'One-Off'), ('Interim Inspection', 'Interim Inspection'), ('Full Batch', 'Full Batch'), ('Complete', 'Complete')], default=None, max_length=20, null=True, verbose_name='Phase'),
        ),
    ]
