# Generated by Django 4.0.4 on 2022-05-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_operation_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='last_change_time',
            new_name='last_action_time',
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Op Name'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='op_note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Note'),
        ),
    ]
