# Generated by Django 4.0.4 on 2022-05-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_last_change_time_operation_last_action_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Complete', 'Complete'), (None, None)], default='Pending', editable=False, max_length=10, null=True, verbose_name='Job Status'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='actual_fullbatch',
            field=models.FloatField(blank=True, null=True, verbose_name='Actual Full Batch'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='actual_insp',
            field=models.FloatField(blank=True, null=True, verbose_name='Actual Inspection'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='actual_oneoff',
            field=models.FloatField(blank=True, null=True, verbose_name='Actual One-Off'),
        ),
    ]
