# Generated by Django 4.0.4 on 2022-05-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_job_status_alter_operation_actual_fullbatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Complete', 'Complete'), (None, None)], default='Pending', editable=False, max_length=10, null=True, verbose_name='Job Status'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Complete', 'Complete'), (None, None)], default='Pending', editable=False, max_length=10, null=True, verbose_name='Op Status'),
        ),
    ]
