# Generated by Django 4.0.4 on 2022-05-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_job_status_alter_operation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='num_scrap',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qty Scrapped'),
        ),
    ]
