# Generated by Django 4.0.4 on 2022-05-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_operation_num_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='help_req',
            field=models.BooleanField(default=False, verbose_name='Help Needed'),
        ),
    ]
